# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b6505619087d1419918e9dfa0d7a3988027c7bac973b8d7aeb3f00fd5620693d5018c03becbe986dca60bd7061eab4082ed0ff28334e07d812b04ebd4202076

test:
  secret_key_base: f36936ca24328d7137bad2907fe533cc4e50f01c066d090dcd630f37e9dfe8a63a3b606f5509f379b5688bfc5869449c93f4833595e2984dce05c7d574c2eef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
